### ISSUE TITLE
Compiled on linux x64. Resyncing from scratch. Getting all block invalidated in log. Can't sync.

### ISSUE THREAD

**Issue by c-cex** [iGotSpots/ECASH-Old-PoWActive#4]

**Comment by iGotSpots** [comment]
Don't comopile from it right now. Definitely do not

**Comment by c-cex** [comment]
Perfect!

**Comment by iGotSpots** [comment]
Sorry, when we reactivated mining, his reward reduction was improperly coded, and I missed the error. I assumed the simplest parameter would work
